spring:
  datasource:
#    url: ${SPRING_DATASOURCE_URL}
#    username: ${SPRING_DATASOURCE_USERNAME}
#    password: ${SPRING_DATASOURCE_PASSWORD}
    url: jdbc:mysql://localhost:3306/mydb?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Tokyo
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  configuration:
    # スネークケースのDBカラム名をSpringのEntity側ではキャメルケースとして対応付けてくれる。
    map-underscore-to-camel-case: true